import manifest from '../lib/images.json';

type Entry = { src: string; w: number };
const MANIFEST = manifest as Record<string, Entry[]>;

interface ShotProps {
  /** Original path as stored in data, e.g. "/work/kitchen.jpg". */
  src: string;
  alt: string;
  className?: string;
  /** The `sizes` attribute: how wide this renders at each breakpoint. */
  sizes?: string;
  loading?: 'lazy' | 'eager';
  draggable?: boolean;
}

/** "/work/kitchen.jpg" -> "work/kitchen" */
function keyFor(src: string) {
  return src.replace(/^\//, '').replace(/\.[^.]+$/, '');
}

/**
 * Highest-resolution derivative for a source path, for consumers that need a
 * single URL rather than a srcset: the lightbox and the video poster. Falls
 * back to the original path when the image is not in the manifest.
 */
export function widestSrc(src: string) {
  const entries = MANIFEST[keyFor(src)];
  return entries?.length ? entries[entries.length - 1].src : src;
}

// Serves the WebP derivatives generated by scripts/optimize-images.mjs, and
// falls back to the original file for anything not in the manifest (the GIF
// avatars, for instance) so a missing entry degrades instead of breaking.
export default function Shot({
  src,
  alt,
  className,
  sizes = '100vw',
  loading = 'lazy',
  draggable,
}: ShotProps) {
  const entries = MANIFEST[keyFor(src)];

  if (!entries?.length) {
    return (
      <img
        src={src}
        alt={alt}
        className={className}
        loading={loading}
        decoding="async"
        draggable={draggable}
      />
    );
  }

  const widest = entries[entries.length - 1];

  return (
    <img
      src={widest.src}
      srcSet={entries.map((e) => `${e.src} ${e.w}w`).join(', ')}
      sizes={sizes}
      alt={alt}
      className={className}
      loading={loading}
      decoding="async"
      draggable={draggable}
    />
  );
}
